site_name: interfere
theme: readthedocs

nav:
  - Home: index.md
  - Simulation: simulation.md
  - Intervention: intervention.md
  - Prediction: prediction.md
  - Optimization: optimization.md
  - Custom forecast methods: custom_forecast_methods.md
  - Benchmark: benchmark.md
  - Extended paper: extended_paper.md

plugins:
  - search
  - bibtex:
      bib_file: "docs/extended_paper.bib"
      bib_by_default: false
      enable_inline_citations: false

markdown_extensions:
  - footnotes
