site_name: interfere
theme: readthedocs

nav:
  - Home: index.md
  - Simulation: simulation.md
  - Intervention: intervention.md
  - Prediction: prediction.md
  - Optimization: optimization.md
  - Custom forecast methods: custom_forecast_methods.md
  - Benchmark: benchmark.md
